### ISSUE TITLE
the SerializerMixin appears to not work with the JSON API adapter :-(

### ISSUE THREAD

**Issue by NullVoxPopuli** [rmachielse/ember-data-paperclip#1]
```
Uncaught TypeError: snapshot.attr(...).get is not a function
serializeAttribute @ serializer-mixin.js:78
superWrapper @ ember.debug.js:23116
(anonymous function) @ json.js:957
(anonymous function) @ attr.js:141
cb @ ember.debug.js:18388
OrderedSet.forEach @ ember.debug.js:18187
...
```

**Comment by NullVoxPopuli** [comment]
I tried removing the mixin from my serializer (cause I'm already just passing the URLs in the AMS serializer)

now my error is in transfoms/file.js

```
serialize: function serialize(deserialized) {
  return deserialized.serialize();
}
```

deserialized is a string. C:\fakepath\filename.png

**Comment by rmachielse** [comment]
@NullVoxPopuli hmm yes I haven't tested this project with other serializers. Your second error is probably caused by setting the whole object instead of the source (see https://github.com/rmachielse/ember-data-paperclip#setting).

Do you think this addon is useful and should be updated?

**Comment by NullVoxPopuli** [comment]
I hope it's useful, but I just haven't gotten it to work yet. File uploading feels like a huge PITA in the JS world :-(

So, I did the setting thing, with this:

```emblem
    = input type='file' value=model.logo onchange='logoChanged'
```

and

```
  action: {
    logoChanged(e) {
      this.get('model.logo').update(e.target.files[0]);
    }
  }
```

but the value set (as shown in ember inspector) is the fakepath, is that right? :-\

**Comment by rmachielse** [comment]
Hmm well are you updating a new model or an existing one? What is the value of `logo` before updating it? It's probably not the right object yet. Maybe we can solve this by using a default value or something:

```javascript
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import File from 'ember-data-paperclip/objects/file';

export default Model.extend({
  logo: attr('file', {
    defaultValue: function() {
      return File.create();
    }
  })
});
```

**Comment by NullVoxPopuli** [comment]
I do think it's useful! I just haven't gotten it working yet :-(

I followed the setting instructions with:

```emblem
    = input type='file' value=model.logo onchange='logoChanged'
```

```js
  action: {
    logoChanged(e) {
      this.get('model.logo').update(e.target.files[0]);
    }
  }
```

but, when I look at the ember inspector, the value of `logo` is the fakepath. Is that right? I thought it was supposed to be a base64 version of the file?

when I click save as-is, I get this error:
` TypeError: deserialized.serialize is not a function`

**Comment by NullVoxPopuli** [comment]
I do think it's useful! I just haven't gotten it working yet :-(

I followed the setting instructions with:

```emblem
    = input type='file' value=model.logo onchange='logoChanged'
```

```js
  action: {
    logoChanged(e) {
      this.get('model.logo').update(e.target.files[0]);
    }
  }
```

but, when I look at the ember inspector, the value of `logo` is the fakepath. Is that right? I thought it was supposed to be a base64 version of the file?

when I click save as-is, I get this error:
` TypeError: deserialized.serialize is not a function`

**Comment by NullVoxPopuli** [comment]
I do think it's useful! I just haven't gotten it working yet :-(

I followed the setting instructions with:

```emblem
    = input type='file' value=model.logo onchange='logoChanged'
```

```js
  action: {
    logoChanged(e) {
      this.get('model.logo').update(e.target.files[0]);
    }
  }
```

but, when I look at the ember inspector, the value of `logo` is the fakepath. Is that right? I thought it was supposed to be a base64 version of the file?

when I click save as-is, I get this error:
` TypeError: deserialized.serialize is not a function`

**Comment by NullVoxPopuli** [comment]
ah ok, this was how I was doing the file:
```js
  logo: attr('file'),
```

I changed it to 

```js
  logo: attr('file',  { defaultValue: function() { return File.create(); } }),
```

but now, when I render the input, I get this error:

```
ember.debug.js:3398 Uncaught InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.```

So, I remove the value (because I set it on an event anyway)

Now I just have:

```emblem
    = input type='file' onchange='logoChanged'
```

and the ember inspector shows <(unknown mixin):..> for the logo field, so that's good.

but!!! my file field isn't actually calling the action I wrote in the controller. :-(

**Comment by NullVoxPopuli** [comment]
ah ok, this was how I was doing the file:
```js
  logo: attr('file'),
```

I changed it to 

```js
  logo: attr('file',  { defaultValue: function() { return File.create(); } }),
```

but now, when I render the input, I get this error:

```
ember.debug.js:3398 Uncaught InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
```

So, I remove the value (because I set it on an event anyway)

Now I just have:

```emblem
    = input type='file' onchange='logoChanged'
```

and the ember inspector shows <(unknown mixin):..> for the logo field, so that's good.

but!!! my file field isn't actually calling the action I wrote in the controller. :-(

**Comment by rmachielse** [comment]
Hmm well I have no experience with Emblem. But I thought you already had the action working?

**Comment by NullVoxPopuli** [comment]
well, it turns out I had a spelling issue. 

But anyway, my action says that e.target is undefined.

for others in the future, my issue was partially that my actions hash was `action` instead of `actions`,
and then I changed my event from onchange to focus-out. (onchange isn't a thing)

```
= input type='file' focus-out='logoChanged'
```

**Comment by NullVoxPopuli** [comment]
oh, when I select a file I do `console.log(e)` and e is the string fakepath. o.o, maybe something is weird.

**Comment by NullVoxPopuli** [comment]
@rmachielse am I supposed to have a custom file-input component, rather than just using a controller action?

**Comment by rmachielse** [comment]
@NullVoxPopuli That's how I use it but it should be possible from a controller as well

**Comment by NullVoxPopuli** [comment]
I don't think it is, after looking over the ember docs. 

I think it would be beneficial for this addon to include that component, if you're willing to share it :-)

**Comment by rmachielse** [comment]
Maybe that's a good idea, I'll think about it

**Comment by NullVoxPopuli** [comment]
or at least a way to import and make our own.

in the mean time, can you share your component here?

**Comment by rmachielse** [comment]
My own is a little more complex because I use a hidden input field, but I think this should work:

```javascript
// app/components/file-upload.js
import Ember from 'ember';

const { TextField } = Ember;

export default TextField.extend({
  type: 'file',

  change(e) {
    this.get('value').update(e.target.files[0]);
  }
});
```
```handlebars
{{!-- app/templates/application.hbs --}}

{{file-upload value=model.logo}}
```

**Comment by rmachielse** [comment]
@NullVoxPopuli I am now also seeing `Uncaught InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.`, That's because the `value` property of a native input can't be an object. I'll update the component

**Comment by NullVoxPopuli** [comment]
ok, so now my problem is that the model isn't getting marked as dirty.

but! good news!!!

I see `logo: "data:image/png;base64,iVBORw0KGg...."` 

in the network panel!!!!
yay!

thanks!

now, is calling update supposed to mark the model as dirty? or should I do that myself?

**Comment by rmachielse** [comment]
@NullVoxPopuli awesome! Maybe I should add that as well. Apparently Ember doesn't recognize the file change itself.

Didn't you see that error btw?

**Comment by NullVoxPopuli** [comment]
yeah, it was because of the value field being set. This is my new component:

```js
import Ember from 'ember';

const { TextField } = Ember;

export default TextField.extend({
  type: 'file',
  model: null,
  property: '',

  change(e) {
    console.log(e);
    let property = this.get('property');
    this.get('model').get(property).update(e.target.files[0]);
  }
});
```

```js
= form/file-upload property='logo' model=model
```

**Comment by rmachielse** [comment]
@NullVoxPopuli I have added a component on master and updated the demo app: https://rmachielse.github.io/ember-data-paperclip/

**Comment by NullVoxPopuli** [comment]
Woo!

**Comment by NullVoxPopuli** [comment]
just to save people the time of research, this is the component I'm using with Ember 2.5

```js
import Ember from 'ember';

const { TextField } = Ember;

export default TextField.extend({
  type: 'file',
  model: null,
  property: '',

  change(e) {
    let property = this.get('property');
    let model = this.get('model');

    model.get(property).update(e.target.files[0]);
    model.send('becomeDirty');
  }
});
```
