### ISSUE TITLE
Error when using model with ember-data-paperclip 'file' transform

### ISSUE THREAD

**Issue by Dak425** [rmachielse/ember-data-paperclip#2]
- **Ember: 2.10.2**
- **Ember Data: 2.12.1**
- **jQuery: 2.2.4**

When I try to use a model that uses the file transform from ember-data-paperclip, I receive this error loading a route that utilizes that model:

**Ember.Object.create only accepts objects.**

The error is thrown on line 35 in ember-data-paperclip/app/transforms/file.js:
```javascript
return File.create(serialized, config.paperclip, assign(copy(attributeMeta), {
      isNew: isEmpty(serialized),
      isEmpty: isEmpty(serialized),
      attributes: Object.keys(serialized || {})
    }));
```

**Comment by rmachielse** [comment]
Hi @Dak425,

What does the payload from the backend look like?

**Comment by Dak425** [comment]
The payload from the backend is a json:api format response from a rails server.

Here is an example response:

```javascript
{
  "data": [
    {
      "id": "1",
      "type": "images",
      "attributes": {
        "title": "LinkedIn",
        "description": "My LinkedIn Profile",
        "created-at": "2017-05-11T02:11:50.924Z",
        "picture": "images/pictures/000/000/001/original/data?1494468710"
      },
      "relationships": {
        "user": {
          "data": {
            "id": "1",
            "type": "admins"
          }
        },
        "sales": {
          "data": []
        },
        "items": {
          "data": []
        }
      }
    }
  ]
}
```

The picture attribute is the actual paperclip attachment column.

**Comment by rmachielse** [comment]
I see, well assuming you want to use the picture attribute with this library, that key should contain a hash with variables that are needed to build the url for the image. For example:

```json
{
  "data": [
    {
      "id": 1,
      "attributes": {
        "picture": {
          "filename": "data"
        }
      }
    }
  ]
}
```

With this config:

```javascript
paperclip: {
  path: 'images/:attachment/:id_partition/:style/:filename.jpg'
}
```

That would give you this:

```javascript
model.get('picture').url('original');

// images/pictures/000/000/001/original/data.jpg
```

**Comment by Dak425** [comment]
Oh hey wow I feel derpy now. I didn't realize that had to be a hash for some reason.

I adjusted my serializer to return a hash for that property and tada.

Thank you for the prompt response, I spent too much time last night trying to figure out what was wrong.

**Comment by rmachielse** [comment]
@Dak425 no problem, glad it works! Let me know if you have any other problems.
